urls:
  - name: 'Harbour API'
    key: 'api'
    # TODO: change to external version of the url
    url: 'https://localhost.myharbourshare.com/api/verifications/health-check'
  - name: 'Harbour Website'
    key: 'website'
    url: 'https://harbourshare.com'
  - name: 'Harbour Docs'
    key: 'docs'
    url: 'https://developers.harbourshare.com'
  - name: 'Harbour WebApp'
    key: 'webapp'
    url: 'https://demo.myharbourshare.com'
