urls:
  - name: 'Harbour API'
    key: 'api'
    url: 'https://localhost.myharbourshare.com/health-check'
  - name: 'Harbour Website'
    key: 'website'
    url: 'https://harbourshare.com'
  - name: 'Harbour Docs'
    key: 'docs'
    url: 'https://developers.harbourshare.com'
  - name: 'Harbour WebApp'
    key: 'webapp'
    url: 'https://demo.myharbourshare.com'
