urls:
  - name: 'Harbour API'
    key: 'api'
    url: 'https://api.harbourshare.com/v2' # TODO: move to api.myharbourshare.com/v2/health once ready
  - name: 'Harbour Website'
    key: 'website'
    url: 'https://harbourshare.com'
  - name: 'Harbour Docs'
    key: 'docs'
    url: 'https://developers.harbourshare.com'
  - name: 'Harbour WebApp'
    key: 'webapp'
    url: 'https://demo.myharbourshare.com'
