name: Scheduled Health Check

# Controls when the action will run.
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '30 * * * *'

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Health Check
    steps:
      - uses: actions/checkout@v4
      - name: Run Health Check Script
        run: |
          success_codes=(200 201 202 203 204 205 206 207 208 226 300 301 302 303 304 305 306 307 308)

          urls=$(yq e '.urls[].url' src/public/config.yaml)
          keys=$(yq e '.urls[].key' src/public/config.yaml)
          echo "[urls]: $urls"
          echo "[keys]: $keys"

          for url in $urls; do
            echo "[url]: $url"

            key=$(echo $keys | cut -d' ' -f1)
            echo "[key]: $key"

            response=$(curl -s -o /dev/null -w "%{http_code}" $url)
            echo "[response]: $response"

            result="failure"
            if [[ ${success_codes[@]} =~ $response ]]; then
              result="failure"
            fi
            echo "[result]: $result"

            date_time=$(date +'%Y-%m-%d %H:%M')
            echo "[date_time] $date_time"
            echo $date_time $result >> "./src/logs/${key}_report.log"

            ls -la ./src/logs
          done
